### ISSUE TITLE
Find PCAP Parser

### ISSUE THREAD

**Issue by cwhitman** [cwhitman/neural-network-intrusion-detection#1]
We need a way to parse pcap files and extract relevant information for our neural network. This will enable us to use our neural network for more or less any type of network traffic, not just ftp log traffic.

**Comment by mborowczak** [comment]
There are some a nice python library for this -
[pcap-parser](https://pypi.python.org/pypi/pcap-parser)
[pcapy](https://pypi.python.org/pypi/pcapy)
[scapy](http://www.secdev.org/projects/scapy/)
[pyshark](https://pypi.python.org/pypi/pyshark)
[python-dpkt](http://www.commercialventvac.com/dpkt.html)

**Comment by cwhitman** [comment]
Finished parsing the pcap files. The python 3 version of scapy, https://github.com/phaethon/scapy, works extremely well. We will likely have to change a few things, like modify what is parsed out, but the overall parsing process works.
