### ISSUE TITLE
Similate DOS/DDOS attacks. 

### ISSUE THREAD

**Issue by cwhitman** [cwhitman/neural-network-intrusion-detection#5]
Even if we end up using real data, it would be beneficial to simulate our own DOS/DDOS attacks for testing purposes. The simulation/s should contain both normal traffic and DOS/DDOS traffic. The simulation data should be recorded in a pcap file.

**Comment by mborowczak** [comment]
We might not need to reinvent the wheel -  and I suggest not reinventing it. Referencing the use of existing tools goes a long way in convincing readers that what you've done is legitimate (if you create a flawed DOS/DDOS simulator your results are also susceptible)

From [stack exchange for sys/net admins/ ServerFault](https://serverfault.com/questions/515908/tools-for-simulating-ddos-attacks)
LOIC (Low Orbit Ion Canon)
XOIC
HULK (HTTP Unbearable Load King)
DDOSIM—Layer 7 DDOS Simulator
R-U-Dead-Yet
Tor’s Hammer
PyLoris
OWASP DOS HTTP POST
DAVOSET
GoldenEye HTTP Denial Of Service Tool

**Comment by cwhitman** [comment]
Marking this as closed. HPing3 as well as LOIC work well for simulated DOS/DDOS traffic. In addition, there is easily accessible DOS traffic from https://ll.mit.edu/ideval/data/1998data.html.

**Comment by hhuru** [comment]
I am trying to working on it. But that AttackLabelParser.py gives error. Second is  I want use that dataset. 
https://www.unsw.adfa.edu.au/australian-centre-for-cyber-security/cybersecurity/ADFA-NB15-Datasets/
